service:
  name: campaign-api
  type: docker

deploy:
  environments:
    - name: dev
      infra: aws-ecs
      markets: [shared]

    - name: qa
      infra: aws-ecs
      markets: [shared]

    - name: stage
      infra: aws-ecs
      markets: [ge, am, maxbet]

    - name: prod
      infra: aws-ecs
      markets: [ge, am, maxbet]

checks:
  lint: true
  test: true
  typecheck: true
