name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: kokajikia/ci-templates/.github/workflows/ci.yaml@main
    with:
      config-path: .pipeline.yaml
    secrets: inherit
