name: Deploy

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag to deploy (commit SHA or version tag like v1.2.0)'
        required: true
        type: string

jobs:
  deploy:
    uses: kokajikia/ci-templates/.github/workflows/deploy.yaml@main
    with:
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit
