name: Deploy

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag (optional — if empty, uses selected branch/tag)'
        required: false
        type: string
        default: ''

jobs:
  deploy:
    uses: kokajikia/ci-templates/.github/workflows/deploy.yaml@main
    with:
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit
